### ISSUE TITLE
Feature: Pass own marked renderer

### ISSUE THREAD

**Issue by tankerkiller125** [Ionaru/simplemde-markdown-editor#2]
### I'm submitting a...
- [ ] Bug report
- [X] Feature request

### Feature Request
I found this fork after going through the network on the original project and as stated in #1 you said that you planned to continue the development of the original project since it seems that the original has stopped.

As noted in the title I would like to pass my own markedjs renderer to simplemde for rendering the previews since marked is what does it in the first place. I think that this should be done with a config property like such:

```js
// Init the default renderer
var renderer = new marked.Renderer();
// Custom table rendering (in this case bootstrap table)
renderer.table = function (header, body) {
     return `<table class="table">${header} ${body}</table>`
};
new SimpleMDE({
    element: document.getElementById('simplemde-box'),
    // Pass the custom renderer
    renderer: renderer
});
```

**Comment by Ionaru** [comment]
I can imagine this feature being useful, I'll look into it.

**Comment by Ionaru** [comment]
This is already possible using the `renderingConfig` option, specifically the `markedOptions` attribute.

Below is an example that renders a pink table.
```js
var renderer = new marked.Renderer();
renderer.table = function (header, body) {
    return '<table class="table" style="background-color: pink;">' + header + body + '</table>'
};

var simplemde = new SimpleMDE({
    element: document.getElementById("new-news-item"),
    renderingConfig: {
        markedOptions: {
            renderer: renderer
        }
    }
});
```

**Comment by tankerkiller125** [comment]
Ah thank you, I was looking through the code looking to see if it was already possible but couldn't and it doesn't seem to be documented in the readme

**Comment by Ionaru** [comment]
It is documented, search the README for `markedOptions`.

**Comment by tankerkiller125** [comment]
I think we might want to reopen this ticket.

I've done the following:

```javascript
var renderer = new marked.Renderer();
        renderer.table = function (header, body) {
            return `<table class="table table-bordered">${header} ${body}</table>`
        };
        renderer.code = function (code, language) {
            if (language != null) {
                return `<pre><code class="test language-${language}">${code}</code></pre>`
            } else {
                return `<pre><code>${code}</code></pre>`
            }
        };
        renderer.image = function (href, title, text) {
            var out = `<img class="img-fluid" src="${href}" alt="${text}"`;
            if (title) {
                out += ` title="${title}"`;
            }
            out += '>';
            return out;
        };
        renderer.blockquote = function (quote) {
            return `<blockquote class="blockquote text-center"><p class="mb-0">${quote}</p></blockquote>`
        };

new SimpleMDE({
            element: document.getElementById('description'),
            renderingConfig: {
                codeSyntaxHighlighting: false,
                markedOptions: {
                    renderer: renderer
                }
            });
```

And the custom HTML I have set in the renderer option is not being used at all. I know that the renderer does work because putting the markdown directly into the markedjs interface with that renderer outputs the custom HTML I've set.
