### ISSUE TITLE
Bug With unordered lists

### ISSUE THREAD

**Issue by rhinoman** [Ionaru/simplemde-markdown-editor#5]
When creating an unordered list like so:
```
- One
- Two
```

entering a newline at the end of line `- One` (i.e., inserting a new item between One and Two) results in the following:

```
- One
- 
NaNundefinedTwo
```

Note: This does not occur with ordered list.  Also, the old SimpleMDE 1.11.2 doesn't have this problem.

**Comment by Ionaru** [comment]
Looks like this was a bug in CodeMirror 5.32.0 (https://github.com/codemirror/CodeMirror/issues/5290), updating the package fixed the issue.

**Comment by rhinoman** [comment]
The fix works.  Thanks!
